use_frameworks!

platform :ios, '9.0'

target 'CCTagLayout_Example' do
  pod 'SDAutoLayout', '~> 2.2.1'
  pod 'CCTagLayout', :path => '../'

  target 'CCTagLayout_Tests' do
    inherit! :search_paths

    
  end
end
